version: '3'
services:
  nginx:
    image: nginx:1.13.7
    container_name: nginx
    depends_on:
      - web
    ports:
      - 5555:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - socket:/code/socket
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    depends_on:
      - mongo
    environment: 
      - MONGO_HOST=mongo
    command: gunicorn --bind unix:socket/floppy.sock -w 2 main:manager
    volumes:
      - socket:/code/socket
  mongo:
    image: "mongo:3.4.22"
    container_name: mongo
volumes:
  socket:
