version: '3'
services:
  nginx:
    image: nginx:1.13.7
    container_name: nginx
    depends_on:
      - web
    networks:
      - my-network
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: flask:0.0.1
    container_name: flask
    volumes:
      - ./:/code/
    environment: 
      - MONGO_HOST=mongo
      - FLASK_APP=/code/app.main:manager
    command: gunicorn -b 0.0.0.0:8000 app.main:manager
    networks:
      my-network:
        aliases:
          - flask-app
  mongo:
    image: "mongo:3.4.22"
    container_name: mongo
    networks:
      my-network:
        aliases:
          - mongo
    
networks:
  my-network: